// keybindings/defaults.rs — Default keybinding table.
//
// Extracted from the keybindings.rs monolith. The add_defaults() data table
// defining every built-in keybinding per context.

use super::*;

impl KeyBindingRegistry {
    pub(crate) fn add_defaults(&mut self) {
        let defaults: Vec<DefaultBinding> = vec![
            // Global bindings
            DefaultBinding {
                key: KeyCode::Char('c'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::Cancel,
                context: BindingContext::Global,
                description: "Cancel current operation",
            },
            DefaultBinding {
                key: KeyCode::Char('q'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::Cancel,
                context: BindingContext::Global,
                description: "Quit application",
            },
            DefaultBinding {
                key: KeyCode::Char('h'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::HistoryPrevious,
                context: BindingContext::Global,
                description: "Previous history",
            },
            DefaultBinding {
                key: KeyCode::Char('l'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::HistoryNext,
                context: BindingContext::Global,
                description: "Next history",
            },
            DefaultBinding {
                key: KeyCode::F(1),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::ShowHelp,
                context: BindingContext::Global,
                description: "Show help",
            },
            DefaultBinding {
                key: KeyCode::Char('p'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::ShowCommandPalette,
                context: BindingContext::Global,
                description: "Command palette",
            },
            DefaultBinding {
                key: KeyCode::Char('v'),
                modifiers: KeyModifiers::ALT,
                action: KeyAction::ToggleVimMode,
                context: BindingContext::Global,
                description: "Toggle Vim mode",
            },
            DefaultBinding {
                key: KeyCode::Char('m'),
                modifiers: KeyModifiers::CONTROL | KeyModifiers::SHIFT,
                action: KeyAction::ShowContextMenu,
                context: BindingContext::Global,
                description: "Show context menu",
            },
            // Prompt bindings
            DefaultBinding {
                key: KeyCode::Enter,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::Submit,
                context: BindingContext::Prompt,
                description: "Submit prompt",
            },
            DefaultBinding {
                key: KeyCode::Enter,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::InsertNewline,
                context: BindingContext::Prompt,
                description: "Insert newline",
            },
            DefaultBinding {
                key: KeyCode::Esc,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::Cancel,
                context: BindingContext::Prompt,
                description: "Cancel",
            },
            DefaultBinding {
                key: KeyCode::Tab,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::CompletionNext,
                context: BindingContext::Prompt,
                description: "Next completion",
            },
            DefaultBinding {
                key: KeyCode::Tab,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::CompletionPrev,
                context: BindingContext::Prompt,
                description: "Previous completion",
            },
            DefaultBinding {
                key: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::HistoryPrevious,
                context: BindingContext::Prompt,
                description: "History previous",
            },
            DefaultBinding {
                key: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::HistoryNext,
                context: BindingContext::Prompt,
                description: "History next",
            },
            DefaultBinding {
                key: KeyCode::Char('p'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::HistoryPrevious,
                context: BindingContext::Prompt,
                description: "History previous",
            },
            DefaultBinding {
                key: KeyCode::Char('n'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::HistoryNext,
                context: BindingContext::Prompt,
                description: "History next",
            },
            DefaultBinding {
                key: KeyCode::Char('r'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::HistorySearch,
                context: BindingContext::Prompt,
                description: "History search",
            },
            DefaultBinding {
                key: KeyCode::Char('a'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::MoveCursorHome,
                context: BindingContext::Prompt,
                description: "Move to start",
            },
            DefaultBinding {
                key: KeyCode::Char('e'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::MoveCursorEnd,
                context: BindingContext::Prompt,
                description: "Move to end",
            },
            DefaultBinding {
                key: KeyCode::Char('b'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::MoveCursorWordLeft,
                context: BindingContext::Prompt,
                description: "Word left",
            },
            DefaultBinding {
                key: KeyCode::Char('f'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::MoveCursorWordRight,
                context: BindingContext::Prompt,
                description: "Word right",
            },
            DefaultBinding {
                key: KeyCode::Char('w'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::DeleteWordLeft,
                context: BindingContext::Prompt,
                description: "Delete word left",
            },
            DefaultBinding {
                key: KeyCode::Char('u'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::DeleteLine,
                context: BindingContext::Prompt,
                description: "Delete line",
            },
            DefaultBinding {
                key: KeyCode::Char('k'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::DeleteToLineEnd,
                context: BindingContext::Prompt,
                description: "Delete to end",
            },
            DefaultBinding {
                key: KeyCode::Char('y'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::Paste,
                context: BindingContext::Prompt,
                description: "Paste",
            },
            DefaultBinding {
                key: KeyCode::Char('z'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::Undo,
                context: BindingContext::Prompt,
                description: "Undo",
            },
            DefaultBinding {
                key: KeyCode::Char('y'),
                modifiers: KeyModifiers::SHIFT | KeyModifiers::CONTROL,
                action: KeyAction::Redo,
                context: BindingContext::Prompt,
                description: "Redo",
            },
            DefaultBinding {
                key: KeyCode::Char('v'),
                modifiers: KeyModifiers::ALT,
                action: KeyAction::VimEnterNormal,
                context: BindingContext::Prompt,
                description: "Enter Vim normal mode",
            },
            DefaultBinding {
                key: KeyCode::Char('v'),
                modifiers: KeyModifiers::ALT,
                action: KeyAction::ToggleVimMode,
                context: BindingContext::Prompt,
                description: "Toggle Vim mode",
            },
            // Vim Normal mode bindings
            DefaultBinding {
                key: KeyCode::Esc,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimEnterNormal,
                context: BindingContext::VimNormal,
                description: "Enter Normal mode",
            },
            DefaultBinding {
                key: KeyCode::Char('i'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimEnterInsert,
                context: BindingContext::VimNormal,
                description: "Enter Insert mode",
            },
            DefaultBinding {
                key: KeyCode::Char('I'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimEnterInsert,
                context: BindingContext::VimNormal,
                description: "Enter Insert at line start",
            },
            DefaultBinding {
                key: KeyCode::Char('a'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimEnterInsert,
                context: BindingContext::VimNormal,
                description: "Enter Insert after cursor",
            },
            DefaultBinding {
                key: KeyCode::Char('A'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimEnterInsert,
                context: BindingContext::VimNormal,
                description: "Enter Insert at line end",
            },
            DefaultBinding {
                key: KeyCode::Char('v'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimEnterVisual,
                context: BindingContext::VimNormal,
                description: "Enter Visual mode",
            },
            DefaultBinding {
                key: KeyCode::Char('V'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimEnterVisualLine,
                context: BindingContext::VimNormal,
                description: "Enter Visual Line mode",
            },
            DefaultBinding {
                key: KeyCode::Char('v'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::VimEnterVisualBlock,
                context: BindingContext::VimNormal,
                description: "Enter Visual Block mode",
            },
            DefaultBinding {
                key: KeyCode::Char(':'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimEnterCommand,
                context: BindingContext::VimNormal,
                description: "Enter Command mode",
            },
            DefaultBinding {
                key: KeyCode::Char('/'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimEnterSearch,
                context: BindingContext::VimNormal,
                description: "Enter Search mode",
            },
            DefaultBinding {
                key: KeyCode::Char('.'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimRepeatLast,
                context: BindingContext::VimNormal,
                description: "Repeat last change",
            },
            // Vim motions
            DefaultBinding {
                key: KeyCode::Char('h'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimMotionLeft,
                context: BindingContext::VimNormal,
                description: "Move left",
            },
            DefaultBinding {
                key: KeyCode::Char('j'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimMotionDown,
                context: BindingContext::VimNormal,
                description: "Move down",
            },
            DefaultBinding {
                key: KeyCode::Char('k'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimMotionUp,
                context: BindingContext::VimNormal,
                description: "Move up",
            },
            DefaultBinding {
                key: KeyCode::Char('l'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimMotionRight,
                context: BindingContext::VimNormal,
                description: "Move right",
            },
            DefaultBinding {
                key: KeyCode::Char('w'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimMotionWordForward,
                context: BindingContext::VimNormal,
                description: "Next word",
            },
            DefaultBinding {
                key: KeyCode::Char('b'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimMotionWordBackward,
                context: BindingContext::VimNormal,
                description: "Previous word",
            },
            DefaultBinding {
                key: KeyCode::Char('e'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimMotionWordEnd,
                context: BindingContext::VimNormal,
                description: "End of word",
            },
            DefaultBinding {
                key: KeyCode::Char('0'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimMotionLineStart,
                context: BindingContext::VimNormal,
                description: "Line start",
            },
            DefaultBinding {
                key: KeyCode::Char('$'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimMotionLineEnd,
                context: BindingContext::VimNormal,
                description: "Line end",
            },
            DefaultBinding {
                key: KeyCode::Char('^'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimMotionLineStart,
                context: BindingContext::VimNormal,
                description: "First non-blank",
            },
            DefaultBinding {
                key: KeyCode::Char('g'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimMotionFileStart,
                context: BindingContext::VimNormal,
                description: "File start",
            },
            DefaultBinding {
                key: KeyCode::Char('G'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimMotionFileEnd,
                context: BindingContext::VimNormal,
                description: "File end",
            },
            DefaultBinding {
                key: KeyCode::Char('u'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::VimMotionPageUp,
                context: BindingContext::VimNormal,
                description: "Page up",
            },
            DefaultBinding {
                key: KeyCode::Char('d'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::VimMotionPageDown,
                context: BindingContext::VimNormal,
                description: "Page down",
            },
            // Vim editing
            DefaultBinding {
                key: KeyCode::Char('x'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimDeleteChar,
                context: BindingContext::VimNormal,
                description: "Delete char",
            },
            DefaultBinding {
                key: KeyCode::Char('X'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimDeleteChar,
                context: BindingContext::VimNormal,
                description: "Delete char left",
            },
            DefaultBinding {
                key: KeyCode::Char('d'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimDeleteLine,
                context: BindingContext::VimNormal,
                description: "Delete line",
            },
            DefaultBinding {
                key: KeyCode::Char('D'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimDeleteLine,
                context: BindingContext::VimNormal,
                description: "Delete to end",
            },
            DefaultBinding {
                key: KeyCode::Char('d'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimDeleteWord,
                context: BindingContext::VimNormal,
                description: "Delete word",
            },
            DefaultBinding {
                key: KeyCode::Char('c'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimChangeLine,
                context: BindingContext::VimNormal,
                description: "Change line",
            },
            DefaultBinding {
                key: KeyCode::Char('C'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimChangeLine,
                context: BindingContext::VimNormal,
                description: "Change to end",
            },
            DefaultBinding {
                key: KeyCode::Char('y'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimYank,
                context: BindingContext::VimNormal,
                description: "Yank line",
            },
            DefaultBinding {
                key: KeyCode::Char('Y'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimYank,
                context: BindingContext::VimNormal,
                description: "Yank to end",
            },
            DefaultBinding {
                key: KeyCode::Char('p'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimPasteAfter,
                context: BindingContext::VimNormal,
                description: "Paste after",
            },
            DefaultBinding {
                key: KeyCode::Char('P'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimPasteBefore,
                context: BindingContext::VimNormal,
                description: "Paste before",
            },
            DefaultBinding {
                key: KeyCode::Char('>'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimIndent,
                context: BindingContext::VimNormal,
                description: "Indent",
            },
            DefaultBinding {
                key: KeyCode::Char('<'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimDedent,
                context: BindingContext::VimNormal,
                description: "Dedent",
            },
            // Vim find
            DefaultBinding {
                key: KeyCode::Char('f'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimFindCharForward,
                context: BindingContext::VimNormal,
                description: "Find char forward",
            },
            DefaultBinding {
                key: KeyCode::Char('F'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimFindCharBackward,
                context: BindingContext::VimNormal,
                description: "Find char backward",
            },
            DefaultBinding {
                key: KeyCode::Char('t'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimFindCharForwardTo,
                context: BindingContext::VimNormal,
                description: "Find to char forward",
            },
            DefaultBinding {
                key: KeyCode::Char('T'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimFindCharBackwardTo,
                context: BindingContext::VimNormal,
                description: "Find to char backward",
            },
            DefaultBinding {
                key: KeyCode::Char(';'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimRepeatFind,
                context: BindingContext::VimNormal,
                description: "Repeat find",
            },
            DefaultBinding {
                key: KeyCode::Char(','),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimRepeatFindReverse,
                context: BindingContext::VimNormal,
                description: "Reverse find",
            },
            // Vim marks
            DefaultBinding {
                key: KeyCode::Char('m'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimSetMark,
                context: BindingContext::VimNormal,
                description: "Set mark",
            },
            DefaultBinding {
                key: KeyCode::Char('\''),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimGoToMark,
                context: BindingContext::VimNormal,
                description: "Go to mark",
            },
            // Vim registers
            DefaultBinding {
                key: KeyCode::Char('"'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimYankRegister,
                context: BindingContext::VimNormal,
                description: "Register operations",
            },
            // Vim Visual mode bindings
            DefaultBinding {
                key: KeyCode::Esc,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimEnterNormal,
                context: BindingContext::VimVisual,
                description: "Exit to Normal mode",
            },
            DefaultBinding {
                key: KeyCode::Char('v'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimEnterVisual,
                context: BindingContext::VimVisual,
                description: "Exit to Normal mode",
            },
            DefaultBinding {
                key: KeyCode::Char('V'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimEnterVisualLine,
                context: BindingContext::VimVisual,
                description: "Visual Line mode",
            },
            DefaultBinding {
                key: KeyCode::Char('v'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::VimEnterVisualBlock,
                context: BindingContext::VimVisual,
                description: "Visual Block mode",
            },
            // Shift+arrows in Visual mode to extend selection
            DefaultBinding {
                key: KeyCode::Up,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimMotionUp,
                context: BindingContext::VimVisual,
                description: "Extend selection up",
            },
            DefaultBinding {
                key: KeyCode::Down,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimMotionDown,
                context: BindingContext::VimVisual,
                description: "Extend selection down",
            },
            DefaultBinding {
                key: KeyCode::Left,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimMotionLeft,
                context: BindingContext::VimVisual,
                description: "Extend selection left",
            },
            DefaultBinding {
                key: KeyCode::Right,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimMotionRight,
                context: BindingContext::VimVisual,
                description: "Extend selection right",
            },
            DefaultBinding {
                key: KeyCode::Char('y'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimYank,
                context: BindingContext::VimVisual,
                description: "Yank selection",
            },
            DefaultBinding {
                key: KeyCode::Char('d'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimDeleteChar,
                context: BindingContext::VimVisual,
                description: "Delete selection",
            },
            DefaultBinding {
                key: KeyCode::Char('c'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimChangeLine,
                context: BindingContext::VimVisual,
                description: "Change selection",
            },
            DefaultBinding {
                key: KeyCode::Char('>'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimIndent,
                context: BindingContext::VimVisual,
                description: "Indent selection",
            },
            DefaultBinding {
                key: KeyCode::Char('<'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimDedent,
                context: BindingContext::VimVisual,
                description: "Dedent selection",
            },
            // Vim Visual Line mode bindings
            DefaultBinding {
                key: KeyCode::Esc,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimEnterNormal,
                context: BindingContext::VimVisualLine,
                description: "Exit to Normal mode",
            },
            DefaultBinding {
                key: KeyCode::Up,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimMotionUp,
                context: BindingContext::VimVisualLine,
                description: "Extend line selection up",
            },
            DefaultBinding {
                key: KeyCode::Down,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimMotionDown,
                context: BindingContext::VimVisualLine,
                description: "Extend line selection down",
            },
            DefaultBinding {
                key: KeyCode::Char('y'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimYank,
                context: BindingContext::VimVisualLine,
                description: "Yank lines",
            },
            DefaultBinding {
                key: KeyCode::Char('d'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimDeleteChar,
                context: BindingContext::VimVisualLine,
                description: "Delete lines",
            },
            // Vim Visual Block mode bindings
            DefaultBinding {
                key: KeyCode::Esc,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimEnterNormal,
                context: BindingContext::VimVisualBlock,
                description: "Exit to Normal mode",
            },
            DefaultBinding {
                key: KeyCode::Up,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimMotionUp,
                context: BindingContext::VimVisualBlock,
                description: "Extend block up",
            },
            DefaultBinding {
                key: KeyCode::Down,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimMotionDown,
                context: BindingContext::VimVisualBlock,
                description: "Extend block down",
            },
            DefaultBinding {
                key: KeyCode::Left,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimMotionLeft,
                context: BindingContext::VimVisualBlock,
                description: "Extend block left",
            },
            DefaultBinding {
                key: KeyCode::Right,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimMotionRight,
                context: BindingContext::VimVisualBlock,
                description: "Extend block right",
            },
            DefaultBinding {
                key: KeyCode::Char('y'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimYank,
                context: BindingContext::VimVisualBlock,
                description: "Yank block",
            },
            DefaultBinding {
                key: KeyCode::Char('d'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimDeleteChar,
                context: BindingContext::VimVisualBlock,
                description: "Delete block",
            },
            // Vim Command mode bindings
            DefaultBinding {
                key: KeyCode::Esc,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimEnterNormal,
                context: BindingContext::VimCommand,
                description: "Exit to Normal mode",
            },
            DefaultBinding {
                key: KeyCode::Char('c'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::VimEnterNormal,
                context: BindingContext::VimCommand,
                description: "Exit to Normal mode",
            },
            DefaultBinding {
                key: KeyCode::Enter,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::Submit,
                context: BindingContext::VimCommand,
                description: "Execute command",
            },
            // Vim Search mode bindings
            DefaultBinding {
                key: KeyCode::Esc,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimEnterNormal,
                context: BindingContext::VimSearch,
                description: "Exit to Normal mode",
            },
            DefaultBinding {
                key: KeyCode::Char('c'),
                modifiers: KeyModifiers::CONTROL,
                action: KeyAction::VimEnterNormal,
                context: BindingContext::VimSearch,
                description: "Exit to Normal mode",
            },
            DefaultBinding {
                key: KeyCode::Enter,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimRepeatLast,
                context: BindingContext::VimSearch,
                description: "Next match",
            },
            DefaultBinding {
                key: KeyCode::Char('n'),
                modifiers: KeyModifiers::NONE,
                action: KeyAction::VimRepeatLast,
                context: BindingContext::VimSearch,
                description: "Next match",
            },
            DefaultBinding {
                key: KeyCode::Char('N'),
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::VimRepeatFindReverse,
                context: BindingContext::VimSearch,
                description: "Previous match",
            },
            // Completion menu bindings
            DefaultBinding {
                key: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::CompletionNext,
                context: BindingContext::Completion,
                description: "Next completion",
            },
            DefaultBinding {
                key: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::CompletionPrev,
                context: BindingContext::Completion,
                description: "Previous completion",
            },
            DefaultBinding {
                key: KeyCode::Tab,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::CompletionNext,
                context: BindingContext::Completion,
                description: "Next completion",
            },
            DefaultBinding {
                key: KeyCode::Tab,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::CompletionPrev,
                context: BindingContext::Completion,
                description: "Previous completion",
            },
            DefaultBinding {
                key: KeyCode::Enter,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::CompletionAccept,
                context: BindingContext::Completion,
                description: "Accept completion",
            },
            DefaultBinding {
                key: KeyCode::Esc,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::CompletionDismiss,
                context: BindingContext::Completion,
                description: "Dismiss completion",
            },
            // Dialog bindings
            DefaultBinding {
                key: KeyCode::Esc,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::Cancel,
                context: BindingContext::Dialog,
                description: "Close dialog",
            },
            DefaultBinding {
                key: KeyCode::Enter,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::Submit,
                context: BindingContext::Dialog,
                description: "Confirm",
            },
            DefaultBinding {
                key: KeyCode::Tab,
                modifiers: KeyModifiers::NONE,
                action: KeyAction::MoveCursorRight,
                context: BindingContext::Dialog,
                description: "Next field",
            },
            DefaultBinding {
                key: KeyCode::Tab,
                modifiers: KeyModifiers::SHIFT,
                action: KeyAction::MoveCursorLeft,
                context: BindingContext::Dialog,
                description: "Previous field",
            },
        ];

        for binding in defaults {
            self.add(binding.into_binding());
        }
    }
}
